name: Compile GPB Package

on:
  workflow_dispatch:
    inputs:
      release_repo:
        type: string
        required: true
        description: "The URL to the GPB repository"
      release_tag:
        type: string
        required: true
        description: "something like debian/ros-humble-geometry-msgs_4.2.3-1_jammy"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: addnab/docker-run-action@v3
      with:
        username: lcas
        password: lincoln
        registry: lcas.lincoln.ac.uk
        image: lcas.lincoln.ac.uk/lcas/docker-dpkg-build:master
        options: -v ${{ github.workspace }}:/package -e GBP_REPO=${{ github.event.inputs.release_repo}} -e GBP_TAG=${{ github.event.inputs.release_tag}}
        run: |
          ./run.sh
    - uses: actions/upload-artifact@v3
      with:
        name: debs
        path: |
          ${{ github.workspace }}/*.deb
          ${{ github.workspace }}/*.ddeb
          ${{ github.workspace }}/*.tar.?z
          ${{ github.workspace }}/*.changes
