name: Compile GPB Package

on:
  workflow_dispatch:
    inputs:
      release_repo:
        type: string
        required: true
        description: "The URL to the GPB repository"
      release_tag:
        type: string
        required: true
        description: "something like debian/ros-humble-geometry-msgs_4.2.3-1_jammy"

run-name: Build "${{ inputs.release_tag }}", invoked by @${{ github.actor }}

jobs:

  build:

    runs-on: lcas

    steps:
    # - uses: addnab/docker-run-action@v3
    #   with:
    #     username: lcas
    #     password: lincoln
    #     registry: lcas.lincoln.ac.uk
    #     image: lcas.lincoln.ac.uk/lcas/docker-dpkg-build:master
    #     options: -v ${{ github.workspace }}:/package -e GBP_REPO=${{ github.event.inputs.release_repo}} -e GBP_TAG=${{ github.event.inputs.release_tag}}
    #     run: |
    #       ./run.sh
    - uses: AutoModality/action-clean@v1
    - name: run docker
      run: |
        docker run --rm -v ${{ github.workspace }}:/package -e GBP_REPO=${{ github.event.inputs.release_repo}} -e GBP_TAG=${{ github.event.inputs.release_tag}} lcas.lincoln.ac.uk/lcas/docker-dpkg-build:master ./run.sh
    - name: "upload to Aptly staging"
      run: |
        APTLY_API="https://lcas.lincoln.ac.uk/apt/api"
        folder=`mktemp -u tmp.XXXXXXXXXXXXXXX`
        repo=lcas_ros_staging
        files=`ls ${{ github.workspace }}/*.deb ${{ github.workspace }}/*.tar.?z ${{ github.workspace }}/*.changes`
        for f in $files; do
          echo "Uploading $f..."
          curl -fsS -X POST -F "file=@$f" -u lcas:${{ secrets.APTLY_TOKEN }} $APTLY_API/files/$folder
        done
        echo "updating staging repo with files in $folder"
        curl -fsS -X POST -u lcas:${{ secrets.APTLY_TOKEN }} $APTLY_API/repos/$repo/file/$folder
        echo "Updating published repo..."
        curl  -X PUT -H 'Content-Type: application/json' --data "{\"SourceKind\": \"local\", \"Sources\": [{\"Name\": \"$repo\"}]}" -u lcas:${{ secrets.APTLY_TOKEN }} $APTLY_API/publish/staging/jammy
        

    - uses: actions/upload-artifact@v3
      with:
        name: debs
        path: |
          ${{ github.workspace }}/*.deb
          ${{ github.workspace }}/*.ddeb
          ${{ github.workspace }}/*.tar.?z
          ${{ github.workspace }}/*.changes
    - uses: AutoModality/action-clean@v1
